### ISSUE TITLE
Failed to process story

### ISSUE THREAD

**Issue by manasgoel2002** [1geek0/neuro-frontend#39]
<img width="871" alt="Screenshot 2024-12-03 at 1 10 44 PM" src="https://github.com/user-attachments/assets/cac404ea-b762-4c65-9b59-b23b550cb3bc">

**Comment by saineshnakra** [comment]
Got this error : 
215-f3b7c4170f307335.js:1 Error in authenticated fetch: I: Missing Refresh Token (audience: 'https://dev-yh7epi8p8mkinedt.us.auth0.com/api/v2/', scope: 'openid profile email offline_access')
    at ea._getTokenUsingRefreshToken (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:40121)
    at async ea._getTokenSilently (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:36342)
    at async ea.getTokenSilently (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:35323)
window.console.error @ 215-f3b7c4170f307335.js:1
215-f3b7c4170f307335.js:1 Error during sign in: I: Missing Refresh Token (audience: 'https://dev-yh7epi8p8mkinedt.us.auth0.com/api/v2/', scope: 'openid profile email offline_access')
    at ea._getTokenUsingRefreshToken (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:40121)
    at async ea._getTokenSilently (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:36342)
    at async ea.getTokenSilently (https://neuro-frontend-seven.vercel.app/_next/static/chunks/459-a573df6ac99042e8.js:1:35323)
window.console.error @ 215-f3b7c4170f307335.js:1
api/story:1 
       Failed to load resource: the server responded with a status of 500 ()
215-f3b7c4170f307335.js:1 Error submitting story: Error: Failed to submit story
    at w (page-dc89c3209b2d9e5a.js:1:4075)
